sudo: required
dist: xenial

node_js-steps: &node_js-steps
  language: node_js
  before_install:
    - if [[ `npm --version` != "6.4.1" ]]; then npm install -g npm@latest; npm --version; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    # https://github.com/Homebrew/homebrew-core/issues/26358
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
    # "brew install" can succeed but return 1 if it has "caveats".
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mongodb || true; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start mongodb; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docker || true; fi
  script: make travis
  after_success:
    - nvm version
    - if [[ ! -z "$DOCKER_USER" ]]; then docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && git checkout -- . && git clean -fd . && make docker_release; fi
  after_script: make report
  services:
    - mongodb
    - docker
matrix:
  allow_failures:
    node_js: "node"
  include:
    - node_js: "10"
      <<: *node_js-steps
    - node_js: "12" # Latest Node is not supported, and recommend, but we'll test it to know incompatibility issues
      <<: *node_js-steps
deploy:
  provider: heroku
  api_key:
    secure: t2CQ7346e/GHyfJuhOEr5gTg5u1a/RrwNzGc9L1xe4pezKH3lbS6pXXKaETPNv3A5OAAvDDTfee5jYV9DsKYPHtTqICwoUkEroDV7TL//jD7tnmrR3pgOVawm9cQoqUx5yFVOCuluL+acq33TNSVqoeYAiqDSgrPtiypajRKplh3C3JrsKUzYdy5MmBU/O3sVoWIF+j4jTNFGlCB21XADKAb5n908Z8sA6UVppKAxgqDubmoruiadDect0+zTP9AZHO1dYO4YddNq32J5/exucGKCf0x5jdT03sWccxNkr9PVtLd3m62yOY/EhbyzvYB6TTY9QtTjsJ5tWwdBV21/wl1oWYptH/q2/b0x5idaiNsEPVxzr9caz0hfrvbL6x5/2Jt8qONCubjMhbL10x867HpB0K2srQjI6UySOk5EDLuOjp3eIIddkYCP1GuBVAy+YQplboV5gUgmQuoqjg7K0VbZbrr7DxmvMcU4gWyoItCweKktxSNAZ5BGDxZMDdxi7b2XpXFbWqmh6twDdtGsnFaWQtOXDzBaB49PYJJDK4b9F61fdTHgh+1A1p6LpAzGtG18JVNBlOdd1l/aqw08qhbBoGwy3UjH7rKnm4A1VowZhuSitSNKNEpyos1snMXaPC0LO+XMYnF6cOqm42va1XCGwxnsPcHGlx076F6jM4=
  app: igicgm-dev
  on:
    repo: szymjaw/cgm-remote-monitor
  
