nightscout:
  build: .
  links:
   - database
   - broker
  ports:
   - "1337:1337"
  environment:
   - MONGO_CONNECTION=mongodb://database/nightscout
   - API_SECRET=mylittlesecret
   - MQTT_MONITOR=mqtt://broker
  command: ./docker-start.sh
database:
  image: mongo:3.0.3
broker:
  image: prologic/mosquitto
  ports:
   - "1883:1883"