nightscout:
  build: ../
  links:
   - database
   - broker
  ports:
   - "1337:1337"
  environment:
   - MONGO_CONNECTION=mongodb://database/nightscout
   - API_SECRET=mylittlesecret
   - MQTT_MONITOR=mqtt://broker
   - PORT=1337
database:
  image: mongo:3.0.3
  ports:
   - "27017"
broker:
  image: prologic/mosquitto
  ports:
   - "1883"